server:
  servlet:
    context-path: /assemble
  port: 8090
spring:
  messages:
    encoding: UTF-8
    basename: classpath:/i18n/messages, classpath:/i18n/error_messages
  devtools:
    livereload:
      enabled: true
  config:
    import:
      - classpath:application-database.yml
      - classpath:application-file.yml
      - classpath:application-value.yml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  file:
    path: D:/shinhan/project/assemble-log